### ISSUE TITLE
False positive on Enabled()

### ISSUE THREAD

**Issue by lzap** [ykadowak/zerologlint#7]
Hello,

I am getting this:

```
zerologlinter: must be dispatched by Msg or Send method (zerologlint)
                                        if logger.Info().Enabled() {
```

I believe this is false positive, or am I missing something in here? Thanks.

**Comment by ykadowak** [comment]
Thank you for reporting.

I think it depends on the context. Can you provide a minimum working example? Or a link to the specific line of the code if it's an OSS?

**Comment by lzap** [comment]
Sure, this is useful when you want to do expensive code and avoid it when level is not set. Example is right in the project README:

https://github.com/rs/zerolog#setting-global-log-level

```
    if e := log.Debug(); e.Enabled() {
        // Compute log output only if enabled.
        value := "bar"
        e.Str("foo", value).Msg("some debug message")
    }
```

**Comment by ykadowak** [comment]
I think this should be fixed and I think I can work on this by the end of this year but right now not possible because of too many other things to work on.

So in the meantime, let me put `help wanted` tag so that someone could potentially work on this.

**Comment by ykadowak** [comment]
@lzap 

I cannot reproduce this at least with this example below. Can you try the latest version? If it persists after trying the latest version, please give me the specific example.

```go
package main

import (
	"github.com/rs/zerolog/log"
)

func main() {
	if e := log.Debug(); e.Enabled() {
		// Compute log output only if enabled.
		value := "bar"
		e.Str("foo", value).Msg("some debug message")
	}
}

```

**Comment by lzap** [comment]
Sure, if you re-enable the linter on one of our projects it will error out:

https://github.com/RHEnVision/provisioning-backend/blob/main/.golangci.yml#L25

**Comment by lzap** [comment]
Let me run it:

```
[lzap@nuc provisioning-backend]$ make fmt
/home/lzap/go/bin/go1.20.10 fmt ./...
/home/lzap/work/provisioning-backend/bin/gofumpt -l -w .
/home/lzap/work/provisioning-backend/bin/goimports -w .
GOROOT=/home/lzap/sdk/go1.20.10 PATH=/home/lzap/sdk/go1.20.10/bin:/home/lzap/.rbenv/shims:/home/lzap/.rbenv/bin:~/Mutt:/home/lzap/.local/bin:/home/lzap/bin:/home/lzap/bin/public:/home/lzap/.npm/bin:/home/lzap/go/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/lzap/.fzf/bin:~/work/foreman-bats GOCACHE=/home/lzap/.cache/go-build /home/lzap/work/provisioning-backend/bin/golangci-lint run --path-prefix /home/lzap/work/provisioning-backend
/home/lzap/work/provisioning-backend/internal/telemetry/zerolog_exporter.go:32:22: zerologlinter: must be dispatched by Msg or Send method (zerologlint)
                t := e.logger.Trace().
                                   ^
/home/lzap/work/provisioning-backend/cmd/pbackend/statuser.go:210:20: zerologlinter: must be dispatched by Msg or Send method (zerologlint)
                                        if logger.Info().Enabled() {
                                                      ^
/home/lzap/work/provisioning-backend/internal/kafka/kafka.go:293:18: zerologlinter: must be dispatched by Msg or Send method (zerologlint)
                if logger.Trace().Enabled() {
                               ^
```

**Comment by ykadowak** [comment]
Thank you for sharing. Confirmed the situation. 

So minimum reproducible example is below.
```go
func falsePositiveOnEnabled() {
	if log.Info().Enabled() {
		log.Info().Str("foo", "bar").Send()
	}
}
```

However, I am not sure if this can be fixed because if we permit the `log.Info().Enabled()`, then below won't be reported based on what I've considered now.

```go
func main() {
	if e := log.Debug(); e.Enabled() {
		value := "bar"
		e.Str("foo", value) // <- this should be reported
	}
}
```

Also it might be a good idea to rewrite your code with this style because then you only have to create `zerolog.Event` once which leads to better performance. What do you think?

Additionally, found another false positive from the repository you provided. This definitely can be and should be fixed. Thanks.
https://github.com/ykadowak/zerologlint/issues/13

**Comment by lzap** [comment]
Thanks for the analysis, I am not going to spend time on this premature optimalization tho. All three cases are in the initialization code which is only called once. We are good, closing cheers!

**Comment by jdemeyer** [comment]
I'm also hitting this when experimenting with `zerologlint` in a large private project.

Wouldn't a good solution be to not warn if the `*zerolog.Event` is assigned to a variable? So a statement like
```
e := log.Debug()
```
would never cause a linter warning.
